package com.bst.sscorp.entities.customerdetails;
// Generated 6 Dec, 2009 5:30:45 PM by Hibernate Tools 3.2.1.GA


import com.bst.sscorp.entities.querydetails.SscorpQueryDetailsT;
import java.util.HashSet;
import java.util.Set;

/**
 * SscorpCustomerDetailsT generated by hbm2java
 */
public class SscorpCustomerDetailsT  implements java.io.Serializable {


     private Integer customerId;
     private String firstName;
     private String lastName;
     private String gender;
     private String emailId;
     private String companyName;
     private String companyWebsite;
     private String phoneNo;
     private String mobileNo;
     private Set<SscorpQueryDetailsT> sscorpQueryDetailsTs = new HashSet<SscorpQueryDetailsT>(0);

    public SscorpCustomerDetailsT() {
    }

	
    public SscorpCustomerDetailsT(String firstName, String gender, String emailId) {
        this.firstName = firstName;
        this.gender = gender;
        this.emailId = emailId;
    }
    public SscorpCustomerDetailsT(String firstName, String lastName, String gender, String emailId, String companyName, String companyWebsite, String phoneNo, String mobileNo, Set<SscorpQueryDetailsT> sscorpQueryDetailsTs) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.gender = gender;
       this.emailId = emailId;
       this.companyName = companyName;
       this.companyWebsite = companyWebsite;
       this.phoneNo = phoneNo;
       this.mobileNo = mobileNo;
       this.sscorpQueryDetailsTs = sscorpQueryDetailsTs;
    }
   
    public Integer getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getCompanyWebsite() {
        return this.companyWebsite;
    }
    
    public void setCompanyWebsite(String companyWebsite) {
        this.companyWebsite = companyWebsite;
    }
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public Set<SscorpQueryDetailsT> getSscorpQueryDetailsTs() {
        return this.sscorpQueryDetailsTs;
    }
    
    public void setSscorpQueryDetailsTs(Set<SscorpQueryDetailsT> sscorpQueryDetailsTs) {
        this.sscorpQueryDetailsTs = sscorpQueryDetailsTs;
    }




}


