package com.bst.sscorp.entities.achievments;
// Generated 23 Dec, 2009 12:05:55 AM by Hibernate Tools 3.2.1.GA


import com.bst.sscorp.entities.companyprofile.SscorpCompanyProfileM;

/**
 * SscorpAchievmentsM generated by hbm2java
 */
public class SscorpAchievmentsM  implements java.io.Serializable {


     private Integer achievmentId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private String achievementName;
     private String superDesc;
     private String achievmentDesc;

    public SscorpAchievmentsM() {
    }

	
    public SscorpAchievmentsM(String achievementName, String achievmentDesc) {
        this.achievementName = achievementName;
        this.achievmentDesc = achievmentDesc;
    }
    public SscorpAchievmentsM(SscorpCompanyProfileM sscorpCompanyProfileM, String achievementName, String superDesc, String achievmentDesc) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.achievementName = achievementName;
       this.superDesc = superDesc;
       this.achievmentDesc = achievmentDesc;
    }
   
    public Integer getAchievmentId() {
        return this.achievmentId;
    }
    
    public void setAchievmentId(Integer achievmentId) {
        this.achievmentId = achievmentId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public String getAchievementName() {
        return this.achievementName;
    }
    
    public void setAchievementName(String achievementName) {
        this.achievementName = achievementName;
    }
    public String getSuperDesc() {
        return this.superDesc;
    }
    
    public void setSuperDesc(String superDesc) {
        this.superDesc = superDesc;
    }
    public String getAchievmentDesc() {
        return this.achievmentDesc;
    }
    
    public void setAchievmentDesc(String achievmentDesc) {
        this.achievmentDesc = achievmentDesc;
    }
}


