/*
Script generated by Aqua Data Studio 4.5.2 on Feb-01-2010 09:16:29 PM
Database: sscorp
Schema: < All Schema >
Objects: TABLE
*/
CREATE TABLE sscorp_address_m ( 
	address_id	int(11) AUTO_INCREMENT NOT NULL,
	address   	varchar(200) NOT NULL,
	city      	varchar(50) NULL,
	province  	varchar(50) NULL,
	country   	varchar(50) NULL,
	zipcode   	varchar(20) NULL,
	company_id	int(11) NULL 
	)
GO
INSERT INTO sscorp_address_m(address_id, address, city, province, country, zipcode, company_id)
  VALUES(1, '1993/1, Katra Lachu Singh, Indu Bazaar, Bhagirath Palace, Chandni Chowk', 'New Delhi', 'Delhi', 'India', '110006', 1)
GO
ALTER TABLE sscorp_address_m
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (address_id)
GO
ALTER TABLE sscorp_address_m
	ADD CONSTRAINT address_m_fk
	FOREIGN KEY(company_id)
	REFERENCES sscorp_companyProfile_m(company_id)
GO
