/*
Script generated by Aqua Data Studio 4.5.2 on Feb-01-2010 09:16:29 PM
Database: sscorp
Schema: < All Schema >
Objects: TABLE
*/
CREATE TABLE sscorp_projects_m ( 
	project_id    	int(11) AUTO_INCREMENT NOT NULL,
	project_name  	varchar(200) NOT NULL,
	project_desc  	varchar(10000) NULL,
	project_cat_id	int(11) NULL 
	)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(1, 'DMRC Dwarika Najafgarh Depot, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(2, 'DMRC Underground ISBT Line, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(3, 'DMRC Mandi Underground Station, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(4, 'BE – 18, DMRC Ashok Nagar Line, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(5, 'BE - 19, DMRC Karkardooma, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(6, 'BE - 21, DMRC Noida, Uttar Pradesh', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(7, 'BE - 22, DMRC Chatarpur, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(8, 'BD - 3, DMRC Sultanpur Depot, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(9, 'BE - 26, DMRC Kirti Nagar, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(10, 'MC1A – DMRC (ISBT to Vishwavidyalya), Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(11, 'DMRC Sarita Vihar Depot, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(12, 'DMRC Azadpur Station, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(13, 'DMRC Akshardham Station, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(14, 'Delhi Dwarika Stations, Delhi', NULL, 1)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(15, 'Delhi International Airport, Delhi', NULL, 2)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(16, 'Hyderabad International, Hyderabad', NULL, 2)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(17, 'Indore Airport, Indore', NULL, 2)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(18, 'Paricha Thermal Power Project, Barmer (Rajasthan)', NULL, 3)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(19, 'Jhajhar Thermal Power Projects, Jhajhar (Haryana)', NULL, 3)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(20, 'Vishnu Paryag Hydro Power Plant – JP Hydro (Uttaranchal)', NULL, 3)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(21, 'HCL, Noida', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(22, 'Bank of America, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(23, 'Genpact, Jaipur', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(24, 'Genpact DMRC IT Park (Shastri Park), Delhi', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(25, 'Hewlett Packard (Global Business Park), Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(26, 'Hewitt International Pvt. Ltd, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(27, 'Nokia, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(28, 'Accenture, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(29, 'Udaan Bhawan Building, Delhi Airport', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(30, 'Bharti Retail, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(31, 'Bharti Airtel, Chandigarh', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(32, 'Welldone Tech Park, Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(33, 'Nokia (SP Infocity), Gurgaon', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(34, 'ASF Buildcon Pvt. Ltd. (Greater Noida), Uttar Pradesh', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(35, 'Reliance Corporate Office (Ajmeri Gate), Delhi', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(36, 'IT Park, Pune', NULL, 4)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(37, 'ITC Hotel Grand Chola, Chennai', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(38, 'DD Resort, Gurgaon', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(39, 'ITC Hotel, Kolkata', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(40, 'ITC Hotel, Bangalore', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(41, 'Hotel Leela, Delhi', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(42, 'Hotel Hans Plaza, Gurgaon', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(43, 'Indus Hotel, Delhi', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(44, 'Restaurant & Recreation Centre, Gurgaon', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(45, 'Citymart Hotel, Gurgaon', NULL, 5)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(46, 'TDI Mall (Rajouri Garden), Delhi', NULL, 6)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(47, 'Westend Mall, Ludhiana', NULL, 6)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(48, 'Westgate Mall (Rajouri Garden), Delhi', NULL, 6)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(49, 'EMR MGF Mall, Gurgaon', NULL, 6)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(50, 'Max Healthcare Hospital (Saket), Delhi', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(51, 'Artemis Hospital, Gurgaon (Apollo Tyre Group)', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(52, 'Medicity, Gurgaon', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(53, 'Fortis Hospital (Vasant Kunj), Delhi', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(54, 'Apollo Hospital, Bhubneshwar', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(55, 'Max Healthcare Hospital (Parparganj), Delhi', NULL, 7)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(56, 'BPTP Central Park, Gurgaon', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(57, 'Mahendra Gesco Residential Complex, Gurgaon', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(58, 'Vatika Group Residential, Gurgaon', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(59, 'Indraprastha Gas Line, Delhi', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(60, 'Mata Vashno Devi Building Project, Jammu', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(61, 'Greater Noida Expo Center Project, Uttar Pradesh', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(62, 'Jaypee Greens (Greater Noida), Uttar Pradesh', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(63, 'PCI, Gurgaon', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(64, 'OIDB, Noida', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(65, 'Commonwealth Games Village, Delhi', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(66, 'Talkatora Stadium, Delhi', NULL, 8)
GO
INSERT INTO sscorp_projects_m(project_id, project_name, project_desc, project_cat_id)
  VALUES(67, 'Ashok Leyland Factory, Rudrapur (Uttrakhand)', NULL, 8)
GO
ALTER TABLE sscorp_projects_m
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (project_id)
GO
ALTER TABLE sscorp_projects_m
	ADD CONSTRAINT project_fk
	FOREIGN KEY(project_cat_id)
	REFERENCES sscorp_project_category_m(project_cat_id)
GO
