/*
Script generated by Aqua Data Studio 4.5.2 on Feb-01-2010 09:16:29 PM
Database: sscorp
Schema: < All Schema >
Objects: TABLE
*/
CREATE TABLE sscorp_menu_m ( 
	menu_id      	int(11) AUTO_INCREMENT NOT NULL,
	menu_name    	varchar(50) NOT NULL,
	menu_position	int(5) NOT NULL,
	menu_url     	varchar(100) NULL,
	company_id   	int(11) NULL 
	)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(1, 'Home', 1, '/home.do', 1)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(2, 'Products and Services', 2, '/fetchProductDetails.do', 1)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(3, 'Profile', 4, '/companyProfile.do', 1)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(4, 'Inquiries', 3, '/showQueryPage.do', 1)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(5, 'Contact Us', 6, '/contactUs.do', 1)
GO
INSERT INTO sscorp_menu_m(menu_id, menu_name, menu_position, menu_url, company_id)
  VALUES(6, 'Projects', 5, '/fetchProjectList.do', 1)
GO
ALTER TABLE sscorp_menu_m
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (menu_id)
GO
ALTER TABLE sscorp_menu_m
	ADD CONSTRAINT menu_m_fk1
	FOREIGN KEY(company_id)
	REFERENCES sscorp_companyProfile_m(company_id)
GO
