/*
Script generated by Aqua Data Studio 4.5.2 on Feb-01-2010 09:16:29 PM
Database: sscorp
Schema: < All Schema >
Objects: TABLE
*/
CREATE TABLE sscorp_products_m ( 
	product_id              	int(11) AUTO_INCREMENT NOT NULL,
	product_name            	varchar(100) NOT NULL,
	product_size            	varchar(50) NOT NULL,
	product_material        	varchar(100) NOT NULL,
	product_finish          	varchar(100) NOT NULL,
	product_photo_attachName	varchar(100) NULL,
	company_id              	int(11) NULL 
	)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(1, 'Junction Box', 'Available in all sizes', 'Cast Iron', 'Black, Hot Dip Galvanized, Electro Galvanized', 'Junction_Box_MS_Black.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(2, 'Deep Junction Box', 'Available in all sizes', 'Cast Iron', 'Black, Hot Dip Galvanized, Electro Galvanized', 'Deep_Junction_Box_MS_Black.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(3, 'Inspection Bend', 'Available in all sizes', 'Cast Iron', 'Black, Hot Dip Galvanized, Electro Galvanized', 'Inspection_Bend_MS_Black.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(4, 'Long Bend', 'Available in all sizes', 'Metal Sheet', 'Black, Hot Dip Galvanized, Electro Galvanized', 'Long_Bend.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(5, 'Saddle', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized, Hot Dip Galvanized', 'Saddle.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(6, 'Saddle with base', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized', 'Saddle_with_base.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(7, 'Checknut', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized', 'Checknut.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(8, 'Reducer', 'Available in all sizes', 'Cast Iron', 'Galvanized', 'Reducer.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(9, 'Sleeve', 'Available in all sizes', 'PVC', 'PVC', 'Sleeve_(Geety).jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(10, 'Wooden Screw', 'Available in all sizes', 'Metal Sheet', 'Galvanized', 'Wooden_Screw.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(11, 'Nipple', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized', 'Nipple.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(12, 'Spacer', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized, Hot Dip Galvanized', 'spacer.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(13, 'Coupler', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized, Hot Dip Galvanized', NULL, 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(14, 'Flexible Pipe', 'Available in all sizes', 'Galvanized Strip', 'Electro Galvanized', 'Flexible_Pipe.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(15, 'Flexible Pipe Coupler', 'Available in all sizes', 'Aluminium Casting', 'Galvanized', 'Strip_Saddle.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(16, 'Strip Saddle', 'Available in all sizes', 'Metal Sheet', 'Electro Galvanized, Hot Dip Galvanized', NULL, 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(17, 'Lighting Chains', 'Available in all sizes', 'Wire', 'Galvanized', 'Lighting_Chains.jpg', 1)
GO
INSERT INTO sscorp_products_m(product_id, product_name, product_size, product_material, product_finish, product_photo_attachName, company_id)
  VALUES(18, 'Ball Socket', 'Available in all sizes', 'Aluminium Casting', 'Galvanized', 'Ball_Socket.jpg', 1)
GO
ALTER TABLE sscorp_products_m
	ADD CONSTRAINT PRIMARY
	PRIMARY KEY (product_id)
GO
ALTER TABLE sscorp_products_m
	ADD CONSTRAINT products_companyProfile_fk
	FOREIGN KEY(company_id)
	REFERENCES sscorp_companyProfile_m(company_id)
GO
