package com.bst.sscorp.entities.menu;
// Generated 6 Dec, 2009 5:30:45 PM by Hibernate Tools 3.2.1.GA

import com.bst.sscorp.entities.companyprofile.*;




/**
 * SscorpMenuM generated by hbm2java
 */
public class SscorpMenuM  implements java.io.Serializable {


     private Integer menuId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private String menuName;
     private int menuPosition;
     private String menuUrl;
     private String additionalMenuUrl;

    public SscorpMenuM() {
    }

	
    public SscorpMenuM(String menuName, int menuPosition) {
        this.menuName = menuName;
        this.menuPosition = menuPosition;
    }
    public SscorpMenuM(SscorpCompanyProfileM sscorpCompanyProfileM, String menuName, int menuPosition, String menuUrl, String additionalMenuUrl) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.menuName = menuName;
       this.menuPosition = menuPosition;
       this.menuUrl = menuUrl;
       this.additionalMenuUrl = additionalMenuUrl;
    }
   
    public Integer getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public int getMenuPosition() {
        return this.menuPosition;
    }
    
    public void setMenuPosition(int menuPosition) {
        this.menuPosition = menuPosition;
    }
    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }
    public String getAdditionalMenuUrl() {
        return this.additionalMenuUrl;
    }

    public void setAdditionalMenuUrl(String additionalMenuUrl) {
        this.additionalMenuUrl = additionalMenuUrl;
    }



}


