package com.bst.sscorp.entities.products;
// Generated 24 Mar, 2010 10:09:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SscorpProductMaterialM generated by hbm2java
 */
public class SscorpProductMaterialM  implements java.io.Serializable {


     private Integer prodMatId;
     private String prodMaterialName;
     private Set<SscorpProductDetailT> sscorpProductDetailTs = new HashSet<SscorpProductDetailT>(0);

    public SscorpProductMaterialM() {
    }

	
    public SscorpProductMaterialM(String prodMaterialName) {
        this.prodMaterialName = prodMaterialName;
    }
    public SscorpProductMaterialM(String prodMaterialName, Set<SscorpProductDetailT> sscorpProductDetailTs) {
       this.prodMaterialName = prodMaterialName;
       this.sscorpProductDetailTs = sscorpProductDetailTs;
    }
   
    public Integer getProdMatId() {
        return this.prodMatId;
    }
    
    public void setProdMatId(Integer prodMatId) {
        this.prodMatId = prodMatId;
    }
    public String getProdMaterialName() {
        return this.prodMaterialName;
    }
    
    public void setProdMaterialName(String prodMaterialName) {
        this.prodMaterialName = prodMaterialName;
    }
    public Set<SscorpProductDetailT> getSscorpProductDetailTs() {
        return this.sscorpProductDetailTs;
    }
    
    public void setSscorpProductDetailTs(Set<SscorpProductDetailT> sscorpProductDetailTs) {
        this.sscorpProductDetailTs = sscorpProductDetailTs;
    }




}


