package com.bst.sscorp.entities.products;
// Generated 24 Mar, 2010 10:09:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SscorpProductDescM generated by hbm2java
 */
public class SscorpProductDescM  implements java.io.Serializable {


     private Integer prodDescId;
     private String prodDescName;
     private Set<SscorpProductDetailT> sscorpProductDetailTs = new HashSet<SscorpProductDetailT>(0);

    public SscorpProductDescM() {
    }

	
    public SscorpProductDescM(String prodDescName) {
        this.prodDescName = prodDescName;
    }
    public SscorpProductDescM(String prodDescName, Set<SscorpProductDetailT> sscorpProductDetailTs) {
       this.prodDescName = prodDescName;
       this.sscorpProductDetailTs = sscorpProductDetailTs;
    }
   
    public Integer getProdDescId() {
        return this.prodDescId;
    }
    
    public void setProdDescId(Integer prodDescId) {
        this.prodDescId = prodDescId;
    }
    public String getProdDescName() {
        return this.prodDescName;
    }
    
    public void setProdDescName(String prodDescName) {
        this.prodDescName = prodDescName;
    }
    public Set<SscorpProductDetailT> getSscorpProductDetailTs() {
        return this.sscorpProductDetailTs;
    }
    
    public void setSscorpProductDetailTs(Set<SscorpProductDetailT> sscorpProductDetailTs) {
        this.sscorpProductDetailTs = sscorpProductDetailTs;
    }




}


