package com.bst.sscorp.entities.products;
// Generated 24 Mar, 2010 10:09:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SscorpProductSizeM generated by hbm2java
 */
public class SscorpProductSizeM  implements java.io.Serializable {


     private Integer prodSizeId;
     private String prodSize;
     private Set<SscorpProductDetailT> sscorpProductDetailTs = new HashSet<SscorpProductDetailT>(0);

    public SscorpProductSizeM() {
    }

	
    public SscorpProductSizeM(String prodSize) {
        this.prodSize = prodSize;
    }
    public SscorpProductSizeM(String prodSize, Set<SscorpProductDetailT> sscorpProductDetailTs) {
       this.prodSize = prodSize;
       this.sscorpProductDetailTs = sscorpProductDetailTs;
    }
   
    public Integer getProdSizeId() {
        return this.prodSizeId;
    }
    
    public void setProdSizeId(Integer prodSizeId) {
        this.prodSizeId = prodSizeId;
    }
    public String getProdSize() {
        return this.prodSize;
    }
    
    public void setProdSize(String prodSize) {
        this.prodSize = prodSize;
    }
    public Set<SscorpProductDetailT> getSscorpProductDetailTs() {
        return this.sscorpProductDetailTs;
    }
    
    public void setSscorpProductDetailTs(Set<SscorpProductDetailT> sscorpProductDetailTs) {
        this.sscorpProductDetailTs = sscorpProductDetailTs;
    }




}


