package com.bst.sscorp.entities.products;
// Generated 24 Mar, 2010 10:09:36 PM by Hibernate Tools 3.2.1.GA


import com.bst.sscorp.entities.companyprofile.SscorpCompanyProfileM;
import java.util.HashSet;
import java.util.Set;

/**
 * SscorpProductsCategoryM generated by hbm2java
 */
public class SscorpProductsCategoryM  implements java.io.Serializable {


     private Integer productCatId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private String productCatName;
     private String prodCatPhotoAttachName;
     private Set<SscorpProductDetailT> sscorpProductDetailTs = new HashSet<SscorpProductDetailT>(0);

    public SscorpProductsCategoryM() {
    }

	
    public SscorpProductsCategoryM(String productCatName) {
        this.productCatName = productCatName;
    }
    public SscorpProductsCategoryM(SscorpCompanyProfileM sscorpCompanyProfileM, String productCatName, String prodCatPhotoAttachName, Set<SscorpProductDetailT> sscorpProductDetailTs) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.productCatName = productCatName;
       this.prodCatPhotoAttachName = prodCatPhotoAttachName;
       this.sscorpProductDetailTs = sscorpProductDetailTs;
    }
   
    public Integer getProductCatId() {
        return this.productCatId;
    }
    
    public void setProductCatId(Integer productCatId) {
        this.productCatId = productCatId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public String getProductCatName() {
        return this.productCatName;
    }
    
    public void setProductCatName(String productCatName) {
        this.productCatName = productCatName;
    }
    public String getProdCatPhotoAttachName() {
        return this.prodCatPhotoAttachName;
    }
    
    public void setProdCatPhotoAttachName(String prodCatPhotoAttachName) {
        this.prodCatPhotoAttachName = prodCatPhotoAttachName;
    }
    public Set<SscorpProductDetailT> getSscorpProductDetailTs() {
        return this.sscorpProductDetailTs;
    }
    
    public void setSscorpProductDetailTs(Set<SscorpProductDetailT> sscorpProductDetailTs) {
        this.sscorpProductDetailTs = sscorpProductDetailTs;
    }




}


