package com.bst.sscorp.entities.products;
// Generated 24 Mar, 2010 10:09:36 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * SscorpProductsM generated by hbm2java
 */
public class SscorpProductsM  implements java.io.Serializable {


     private Integer productId;
     private String productName;
     private Set<SscorpProductDetailT> sscorpProductDetailTs = new HashSet<SscorpProductDetailT>(0);

    public SscorpProductsM() {
    }

	
    public SscorpProductsM(String productName) {
        this.productName = productName;
    }
    public SscorpProductsM(String productName, Set<SscorpProductDetailT> sscorpProductDetailTs) {
       this.productName = productName;
       this.sscorpProductDetailTs = sscorpProductDetailTs;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public Set<SscorpProductDetailT> getSscorpProductDetailTs() {
        return this.sscorpProductDetailTs;
    }
    
    public void setSscorpProductDetailTs(Set<SscorpProductDetailT> sscorpProductDetailTs) {
        this.sscorpProductDetailTs = sscorpProductDetailTs;
    }




}


