package com.bst.sscorp.entities.querydetails;
// Generated 6 Dec, 2009 5:30:45 PM by Hibernate Tools 3.2.1.GA


import com.bst.sscorp.entities.companyprofile.*;
import com.bst.sscorp.entities.customerdetails.SscorpCustomerDetailsT;
import java.util.Date;

/**
 * SscorpQueryDetailsT generated by hbm2java
 */
public class SscorpQueryDetailsT  implements java.io.Serializable {


     private Integer queryId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private SscorpCustomerDetailsT sscorpCustomerDetailsT;
     private String query;
     private String querySubject;
     private Date queryDate;
     private String hearAboutUs;

    public SscorpQueryDetailsT() {
    }

	
    public SscorpQueryDetailsT(String query, Date queryDate) {
        this.query = query;
        this.queryDate = queryDate;
    }
    public SscorpQueryDetailsT(SscorpCompanyProfileM sscorpCompanyProfileM, SscorpCustomerDetailsT sscorpCustomerDetailsT, String query, String querySubject, Date queryDate, String hearAboutUs) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.sscorpCustomerDetailsT = sscorpCustomerDetailsT;
       this.query = query;
       this.querySubject = querySubject;
       this.queryDate = queryDate;
       this.hearAboutUs = hearAboutUs;
    }
   
    public Integer getQueryId() {
        return this.queryId;
    }
    
    public void setQueryId(Integer queryId) {
        this.queryId = queryId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public SscorpCustomerDetailsT getSscorpCustomerDetailsT() {
        return this.sscorpCustomerDetailsT;
    }
    
    public void setSscorpCustomerDetailsT(SscorpCustomerDetailsT sscorpCustomerDetailsT) {
        this.sscorpCustomerDetailsT = sscorpCustomerDetailsT;
    }
    public String getQuery() {
        return this.query;
    }
    
    public void setQuery(String query) {
        this.query = query;
    }
    public String getQuerySubject() {
        return this.querySubject;
    }
    
    public void setQuerySubject(String querySubject) {
        this.querySubject = querySubject;
    }
    public Date getQueryDate() {
        return this.queryDate;
    }
    
    public void setQueryDate(Date queryDate) {
        this.queryDate = queryDate;
    }
    public String getHearAboutUs() {
        return this.hearAboutUs;
    }
    
    public void setHearAboutUs(String hearAboutUs) {
        this.hearAboutUs = hearAboutUs;
    }




}


