package com.bst.sscorp.entities.companyprofile;
// Generated 23 Dec, 2009 12:05:55 AM by Hibernate Tools 3.2.1.GA


import com.bst.sscorp.entities.address.SscorpAddressM;
import com.bst.sscorp.entities.achievments.*;
import com.bst.sscorp.entities.mobilenumbers.SscorpPhoneNumbersM;
import com.bst.sscorp.entities.products.SscorpProductsCategoryM;
import com.bst.sscorp.entities.projects.SscorpProjectCategoryM;
import java.util.HashSet;
import java.util.Set;

/**
 * SscorpCompanyProfileM generated by hbm2java
 */
public class SscorpCompanyProfileM  implements java.io.Serializable {


     private Integer companyId;
     private String companyName;
     private String founderName;
     private String coFoundersName;
     private String presentCeo;
     private String companyPhone;
     private String emailId;
     private String companyLogoAttachName;
     private String companyPunchLine;
     private String aboutUs;
     private String faxNumber;
     private String infrastructure;
     private String achievmentsDesc;
     private String projectsDesc;
     private Set<SscorpAddressM> sscorpAddressMs = new HashSet<SscorpAddressM>(0);
     private Set<SscorpAchievmentsM> sscorpAchievmentsMs = new HashSet<SscorpAchievmentsM>(0);
     private Set<SscorpPhoneNumbersM> sscorpPhoneNumbersMs = new HashSet<SscorpPhoneNumbersM>(0);
     private Set<SscorpProjectCategoryM> sscorpProjectCategoryMs = new HashSet<SscorpProjectCategoryM>(0);
     private Set<SscorpProductsCategoryM> sscorpProductsCategoryMs = new HashSet<SscorpProductsCategoryM>(0);

    public SscorpCompanyProfileM() {
    }

	
    public SscorpCompanyProfileM(String companyName, String founderName, String presentCeo, String emailId, String aboutUs) {
        this.companyName = companyName;
        this.founderName = founderName;
        this.presentCeo = presentCeo;
        this.emailId = emailId;
        this.aboutUs = aboutUs;
    }
    public SscorpCompanyProfileM(String companyName, String founderName, String coFoundersName, String presentCeo,
                                    String companyPhone, String emailId, String companyLogoAttachName,
                                    String companyPunchLine, String aboutUs, String faxNumber,
                                    String infrastructure, String achievmentsDesc, String projectsDesc,
                                    Set<SscorpAddressM> sscorpAddressMs, Set<SscorpAchievmentsM> sscorpAchievmentsMs,
                                    Set<SscorpPhoneNumbersM> sscorpPhoneNumbersMs,
                                    Set<SscorpProjectCategoryM> sscorpProjectCategoryMs,
                                    Set<SscorpProductsCategoryM> sscorpProductsCategoryMs) {
       this.companyName = companyName;
       this.founderName = founderName;
       this.coFoundersName = coFoundersName;
       this.presentCeo = presentCeo;
       this.companyPhone = companyPhone;
       this.emailId = emailId;
       this.companyLogoAttachName = companyLogoAttachName;
       this.companyPunchLine = companyPunchLine;
       this.aboutUs = aboutUs;
       this.faxNumber = faxNumber;
       this.infrastructure= infrastructure;
       this.achievmentsDesc = achievmentsDesc;
       this.projectsDesc = projectsDesc;
       this.sscorpAddressMs = sscorpAddressMs;
       this.sscorpAchievmentsMs = sscorpAchievmentsMs;
       this.sscorpPhoneNumbersMs = sscorpPhoneNumbersMs;
       this.sscorpProjectCategoryMs = sscorpProjectCategoryMs;
       this.sscorpProductsCategoryMs = sscorpProductsCategoryMs;
    }
   
    public Integer getCompanyId() {
        return this.companyId;
    }
    
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    public String getFounderName() {
        return this.founderName;
    }
    
    public void setFounderName(String founderName) {
        this.founderName = founderName;
    }
    public String getCoFoundersName() {
        return this.coFoundersName;
    }
    
    public void setCoFoundersName(String coFoundersName) {
        this.coFoundersName = coFoundersName;
    }
    public String getPresentCeo() {
        return this.presentCeo;
    }
    
    public void setPresentCeo(String presentCeo) {
        this.presentCeo = presentCeo;
    }
    public String getCompanyPhone() {
        return this.companyPhone;
    }
    
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getCompanyLogoAttachName() {
        return this.companyLogoAttachName;
    }
    
    public void setCompanyLogoAttachName(String companyLogoAttachName) {
        this.companyLogoAttachName = companyLogoAttachName;
    }
    public String getCompanyPunchLine() {
        return this.companyPunchLine;
    }
    
    public void setCompanyPunchLine(String companyPunchLine) {
        this.companyPunchLine = companyPunchLine;
    }
    public String getAboutUs() {
        return this.aboutUs;
    }
    
    public void setAboutUs(String aboutUs) {
        this.aboutUs = aboutUs;
    }
    public Set<SscorpAddressM> getSscorpAddressMs() {
        return this.sscorpAddressMs;
    }
    
    public void setSscorpAddressMs(Set<SscorpAddressM> sscorpAddressMs) {
        this.sscorpAddressMs = sscorpAddressMs;
    }
    public Set<SscorpAchievmentsM> getSscorpAchievmentsMs() {
        return this.sscorpAchievmentsMs;
    }
    
    public void setSscorpAchievmentsMs(Set<SscorpAchievmentsM> sscorpAchievmentsMs) {
        this.sscorpAchievmentsMs = sscorpAchievmentsMs;
    }

    /**
     * @return the faxNumber
     */
    public String getFaxNumber() {
        return faxNumber;
    }

    /**
     * @param faxNumber the faxNumber to set
     */
    public void setFaxNumber(String faxNumber) {
        this.faxNumber = faxNumber;
    }

    public Set<SscorpPhoneNumbersM> getSscorpPhoneNumbersMs() {
        return this.sscorpPhoneNumbersMs;
    }

    public void setSscorpPhoneNumbersMs(Set<SscorpPhoneNumbersM> sscorpPhoneNumbersMs) {
        this.sscorpPhoneNumbersMs = sscorpPhoneNumbersMs;
    }

    /**
     * @return the infrastructure
     */
    public String getInfrastructure() {
        return infrastructure;
    }

    /**
     * @param infrastructure the infrastructure to set
     */
    public void setInfrastructure(String infrastructure) {
        this.infrastructure = infrastructure;
    }

    public String getAchievmentsDesc() {
        return this.achievmentsDesc;
    }

    public void setAchievmentsDesc(String achievmentsDesc) {
        this.achievmentsDesc = achievmentsDesc;
    }

    public String getProjectsDesc() {
        return this.projectsDesc;
    }

    public void setProjectsDesc(String projectsDesc) {
        this.projectsDesc = projectsDesc;
    }
    public Set<SscorpProjectCategoryM> getSscorpProjectCategoryMs() {
        return this.sscorpProjectCategoryMs;
    }

    public void setSscorpProjectCategoryMs(Set<SscorpProjectCategoryM> sscorpProjectCategoryMs) {
        this.sscorpProjectCategoryMs = sscorpProjectCategoryMs;
    }

    public Set<SscorpProductsCategoryM> getSscorpProductsCategoryMs() {
        return this.sscorpProductsCategoryMs;
    }

    public void setSscorpProductsCategoryMs(Set<SscorpProductsCategoryM> sscorpProductsCategoryMs) {
        this.sscorpProductsCategoryMs = sscorpProductsCategoryMs;
    }
}


