package com.bst.sscorp.entities.address;
// Generated 23 Dec, 2009 12:05:55 AM by Hibernate Tools 3.2.1.GA

import com.bst.sscorp.entities.companyprofile.SscorpCompanyProfileM;
import com.bst.sscorp.entities.projects.SscorpProjectsM;
import java.util.HashSet;
import java.util.Set;

/**
 * SscorpAddressM generated by hbm2java
 */
public class SscorpAddressM  implements java.io.Serializable {


     private Integer addressId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private String address;
     private String city;
     private String province;
     private String country;
     private String zipcode;
     private Set<SscorpProjectsM> sscorpProjectsMs = new HashSet<SscorpProjectsM>(0);

    public SscorpAddressM() {
    }

	
    public SscorpAddressM(String address) {
        this.address = address;
    }
    public SscorpAddressM(SscorpCompanyProfileM sscorpCompanyProfileM, String address, String city, String province, String country, String zipcode, Set<SscorpProjectsM> sscorpProjectsMs) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.address = address;
       this.city = city;
       this.province = province;
       this.country = country;
       this.zipcode = zipcode;
       this.sscorpProjectsMs = sscorpProjectsMs;
    }
   
    public Integer getAddressId() {
        return this.addressId;
    }
    
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }
    public Set<SscorpProjectsM> getSscorpProjectsMs() {
        return this.sscorpProjectsMs;
    }

    public void setSscorpProjectsMs(Set<SscorpProjectsM> sscorpProjectsMs) {
        this.sscorpProjectsMs = sscorpProjectsMs;
    }



}


