package com.bst.sscorp.entities.mobilenumbers;
// Generated 9 Apr, 2010 10:05:07 PM by Hibernate Tools 3.2.1.GA

import com.bst.sscorp.entities.companyprofile.SscorpCompanyProfileM;




/**
 * SscorpPhoneNumbersM generated by hbm2java
 */
public class SscorpPhoneNumbersM  implements java.io.Serializable {


     private Integer phoneId;
     private SscorpCompanyProfileM sscorpCompanyProfileM;
     private String phoneOwner;
     private String countryCode;
     private String stdCode;
     private String phoneNumber;

    public SscorpPhoneNumbersM() {
    }

	
    public SscorpPhoneNumbersM(String phoneOwner, String phoneNumber) {
        this.phoneOwner = phoneOwner;
        this.phoneNumber = phoneNumber;
    }
    public SscorpPhoneNumbersM(SscorpCompanyProfileM sscorpCompanyProfileM, String phoneOwner, String countryCode, String stdCode, String phoneNumber) {
       this.sscorpCompanyProfileM = sscorpCompanyProfileM;
       this.phoneOwner = phoneOwner;
       this.countryCode = countryCode;
       this.stdCode = stdCode;
       this.phoneNumber = phoneNumber;
    }
   
    public Integer getPhoneId() {
        return this.phoneId;
    }
    
    public void setPhoneId(Integer phoneId) {
        this.phoneId = phoneId;
    }
    public SscorpCompanyProfileM getSscorpCompanyProfileM() {
        return this.sscorpCompanyProfileM;
    }
    
    public void setSscorpCompanyProfileM(SscorpCompanyProfileM sscorpCompanyProfileM) {
        this.sscorpCompanyProfileM = sscorpCompanyProfileM;
    }
    public String getPhoneOwner() {
        return this.phoneOwner;
    }
    
    public void setPhoneOwner(String phoneOwner) {
        this.phoneOwner = phoneOwner;
    }
    public String getCountryCode() {
        return this.countryCode;
    }
    
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode;
    }
    public String getStdCode() {
        return this.stdCode;
    }
    
    public void setStdCode(String stdCode) {
        this.stdCode = stdCode;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }




}


