package com.bst.sscorp.entities.projects;
// Generated 6 Apr, 2010 7:32:14 AM by Hibernate Tools 3.2.1.GA

import com.bst.sscorp.entities.address.SscorpAddressM;




/**
 * SscorpProjectsM generated by hbm2java
 */
public class SscorpProjectsM  implements java.io.Serializable {


     private Integer projectId;
     private SscorpAddressM sscorpAddressM;
     private SscorpProjectCategoryM sscorpProjectCategoryM;
     private String projectName;

    public SscorpProjectsM() {
    }

	
    public SscorpProjectsM(String projectName) {
        this.projectName = projectName;
    }
    public SscorpProjectsM(SscorpAddressM sscorpAddressM, SscorpProjectCategoryM sscorpProjectCategoryM, String projectName) {
       this.sscorpAddressM = sscorpAddressM;
       this.sscorpProjectCategoryM = sscorpProjectCategoryM;
       this.projectName = projectName;
    }
   
    public Integer getProjectId() {
        return this.projectId;
    }
    
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
    public SscorpAddressM getSscorpAddressM() {
        return this.sscorpAddressM;
    }
    
    public void setSscorpAddressM(SscorpAddressM sscorpAddressM) {
        this.sscorpAddressM = sscorpAddressM;
    }
    public SscorpProjectCategoryM getSscorpProjectCategoryM() {
        return this.sscorpProjectCategoryM;
    }
    
    public void setSscorpProjectCategoryM(SscorpProjectCategoryM sscorpProjectCategoryM) {
        this.sscorpProjectCategoryM = sscorpProjectCategoryM;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }




}


